export const manufacturers = [
  "Abarth",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Bugatti",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Dacia",
  "Daewoo",
  "Daihatsu",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hummer",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Koenigsegg",
  "Lamborghini",
  "Lancia",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Lotus",
  "Maserati",
  "Maybach",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "Mini",
  "Mitsubishi",
  "Nissan",
  "Opel",
  "Pagani",
  "Peugeot",
  "Pontiac",
  "Porsche",
  "Ram",
  "Renault",
  "Rolls-Royce",
  "Saab",
  "Saturn",
  "Scion",
  "Seat",
  "Skoda",
  "Smart",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
  "Acura",
  "Geely",
  "BYD",
  "Chery",
  "Great Wall Motors",
  "MG Motor",
  "Proton",
  "Tata Motors",
  "Mahindra",
  "Maruti Suzuki",
  "Isuzu",
  "FAW",
  "Haval",
  "Dongfeng",
  "BAIC",
  "JAC Motors",
  "Brilliance Auto",
  "Zotye",
  "Genesis",
  "Ram",
  "Polestar",
  "Rivian",
  "Lucid Motors",
  "NIO",
  "Byton",
  "Lynk & Co",
  "Rimac",
  "Wuling",
  "Xpeng Motors",
  "Faraday Future",
  "VinFast",
  "Seres",
  "Lucra Cars",
  "Lykan Hypersport",
  "Rimac Automobili",
  "Naran Automotive",
  "Rezvani Motors",
  "Zenvo Automotive",
];

// export function afficherKilometrages() {
//   let kilometer = [];
//   for (let kilometrage = 0; kilometrage <= 300000; kilometrage += 10000) {
//     kilometer.push(kilometrage);
//   }
//   return kilometer;
// }

export const yearsOfProduction = [
  { title: "Année", value: "" },
  { title: "1992", value: "1992" },
  { title: "1993", value: "1993" },
  { title: "1994", value: "1994" },
  { title: "1995", value: "1995" },
  { title: "1996", value: "1996" },
  { title: "1997", value: "1997" },
  { title: "1998", value: "1998" },
  { title: "1999", value: "1999" },
  { title: "2000", value: "2000" },
  { title: "2001", value: "2001" },
  { title: "2002", value: "2002" },
  { title: "2003", value: "2003" },
  { title: "2004", value: "2004" },
  { title: "2005", value: "2005" },
  { title: "2006", value: "2006" },
  { title: "2007", value: "2007" },
  { title: "2008", value: "2008" },
  { title: "2009", value: "2009" },
  { title: "2010", value: "2010" },
  { title: "2011", value: "2011" },
  { title: "2012", value: "2012" },
  { title: "2013", value: "2013" },
  { title: "2014", value: "2014" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
];

export const fuels = [
  {
    title: "Carburant",
    value: "",
  },
  {
    title: "Diesel",
    value: "Diesel",
  },
  {
    title: "Essance",
    value: "Essance",
  },
  {
    title: "Éléctrique",
    value: "Éléctrique",
  },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
