import { CarDataProps } from "../types";

export const mockCars: CarDataProps[] = [
  {
    title: "Peugeot 208 Active",
    marque: "Peugeot",
    modele: "208",
    reference: "PEU-208-2019-001",
    version: "1.2 PureTech 75",
    prixttcaffiche: 12490,
    kilometrage: 48500,
    anneemodele: "2019",
    energie: "Essence",
    carrosserie: "Citadine",
    nbrplace: 5,
    nbrporte: 5,
    couleurexterieur: "Bleu",
    puissancefiscale: 4,
    puissancedyn: 75,
    categorie: "Particulier",
    typeboite: "Manuelle",
    description: "Citadine moderne, faible consommation, parfait pour la ville.",
    datemes: "2020-03-15",
    photos: { photo: ["/MKB-automobile-Trouvez-votre-voiture-600-400.webp"] },
    ville: "Paris",
  },
  {
    title: "Renault Clio Intens",
    marque: "Renault",
    modele: "Clio",
    reference: "REN-CLI-2020-002",
    version: "1.0 TCe 90",
    prixttcaffiche: 13490,
    kilometrage: 39000,
    anneemodele: "2020",
    energie: "Essence",
    carrosserie: "Citadine",
    nbrplace: 5,
    nbrporte: 5,
    couleurexterieur: "Rouge",
    puissancefiscale: 5,
    puissancedyn: 90,
    categorie: "Particulier",
    typeboite: "Manuelle",
    description: "Équipement riche, aide à la conduite, très bon état.",
    datemes: "2021-01-22",
    photos: { photo: ["/no-img.png"] },
    ville: "Lyon",
  },
  {
    title: "Volkswagen Golf Confortline",
    marque: "Volkswagen",
    modele: "Golf",
    reference: "VW-GOL-2018-003",
    version: "1.6 TDI 115",
    prixttcaffiche: 15990,
    kilometrage: 78000,
    anneemodele: "2018",
    energie: "Diesel",
    carrosserie: "Compacte",
    nbrplace: 5,
    nbrporte: 5,
    couleurexterieur: "Gris",
    puissancefiscale: 6,
    puissancedyn: 115,
    categorie: "Particulier",
    typeboite: "Manuelle",
    description: "Référence des compactes, confortable et sobre sur route.",
    datemes: "2019-06-03",
    photos: { photo: ["/no-img.png"] },
    ville: "Nantes",
  },
  {
    title: "BMW Série 1 M Sport",
    marque: "BMW",
    modele: "Série 1",
    reference: "BMW-1-2017-004",
    version: "118i 136",
    prixttcaffiche: 18490,
    kilometrage: 86500,
    anneemodele: "2017",
    energie: "Essence",
    carrosserie: "Compacte",
    nbrplace: 5,
    nbrporte: 5,
    couleurexterieur: "Blanc",
    puissancefiscale: 7,
    puissancedyn: 136,
    categorie: "Particulier",
    typeboite: "Automatique",
    description: "Finition M Sport, look dynamique, agréable à conduire.",
    datemes: "2018-05-10",
    photos: { photo: ["/no-img.png"] },
    ville: "Toulouse",
  },
  {
    title: "Audi A3 Sportback Design",
    marque: "Audi",
    modele: "A3",
    reference: "AUD-A3-2019-005",
    version: "35 TFSI 150",
    prixttcaffiche: 21990,
    kilometrage: 52000,
    anneemodele: "2019",
    energie: "Essence",
    carrosserie: "Berline",
    nbrplace: 5,
    nbrporte: 5,
    couleurexterieur: "Noir",
    puissancefiscale: 8,
    puissancedyn: 150,
    categorie: "Particulier",
    typeboite: "Automatique",
    description: "Qualité perçue Audi, très bien équipée.",
    datemes: "2020-09-02",
    photos: { photo: ["/audi-a3-sportback-35-tfsi-150-s-tronic-7-neuf-2022-fleury-les-aubrais-1.png"] },
    ville: "Bordeaux",
  },
  {
    title: "Tesla Model 3 Standard Range",
    marque: "Tesla",
    modele: "Model 3",
    reference: "TES-M3-2021-006",
    version: "RWD",
    prixttcaffiche: 28990,
    kilometrage: 31000,
    anneemodele: "2021",
    energie: "Éléctrique",
    carrosserie: "Berline",
    nbrplace: 5,
    nbrporte: 4,
    couleurexterieur: "Blanc nacré",
    puissancefiscale: 9,
    puissancedyn: 239,
    categorie: "Particulier",
    typeboite: "Automatique",
    description: "Électrique, conduite autonome, très faible coût d’usage.",
    datemes: "2022-02-14",
    photos: { photo: ["/no-img.png"] },
    ville: "Lille",
  },
  {
    title: "Dacia Sandero Stepway",
    marque: "Dacia",
    modele: "Sandero",
    reference: "DAC-SAN-2018-007",
    version: "TCe 90",
    prixttcaffiche: 9990,
    kilometrage: 60500,
    anneemodele: "2018",
    energie: "Essence",
    carrosserie: "Citadine",
    nbrplace: 5,
    nbrporte: 5,
    couleurexterieur: "Gris clair",
    puissancefiscale: 5,
    puissancedyn: 90,
    categorie: "Particulier",
    typeboite: "Manuelle",
    description: "Excellent rapport qualité/prix.",
    datemes: "2019-03-30",
    photos: { photo: ["/no-img.png"] },
    ville: "Rennes",
  },
  {
    title: "Ford Kuga Titanium",
    marque: "Ford",
    modele: "Kuga",
    reference: "FOR-KUG-2017-008",
    version: "1.5 TDCi 120",
    prixttcaffiche: 14990,
    kilometrage: 99000,
    anneemodele: "2017",
    energie: "Diesel",
    carrosserie: "SUV",
    nbrplace: 5,
    nbrporte: 5,
    couleurexterieur: "Bleu foncé",
    puissancefiscale: 6,
    puissancedyn: 120,
    categorie: "Particulier",
    typeboite: "Manuelle",
    description: "SUV familial, bonne habitabilité.",
    datemes: "2018-07-18",
    photos: { photo: ["/no-img.png"] },
    ville: "Strasbourg",
  },
  {
    title: "Citroën C3 Shine",
    marque: "Citroën",
    modele: "C3",
    reference: "CIT-C3-2019-009",
    version: "1.2 PureTech 82",
    prixttcaffiche: 11490,
    kilometrage: 50500,
    anneemodele: "2019",
    energie: "Essence",
    carrosserie: "Citadine",
    nbrplace: 5,
    nbrporte: 5,
    couleurexterieur: "Blanc",
    puissancefiscale: 4,
    puissancedyn: 82,
    categorie: "Particulier",
    typeboite: "Manuelle",
    description: "Citadine avec options de confort.",
    datemes: "2020-05-05",
    photos: { photo: ["/citadine.webp"] },
    ville: "Montpellier",
  },
  {
    title: "Mercedes-Benz Classe A",
    marque: "Mercedes-Benz",
    modele: "Classe A",
    reference: "MER-A-2018-010",
    version: "A 180 d",
    prixttcaffiche: 22990,
    kilometrage: 72000,
    anneemodele: "2018",
    energie: "Diesel",
    carrosserie: "Compacte",
    nbrplace: 5,
    nbrporte: 5,
    couleurexterieur: "Noir",
    puissancefiscale: 6,
    puissancedyn: 116,
    categorie: "Particulier",
    typeboite: "Automatique",
    description: "Technologie embarquée et confort premium.",
    datemes: "2019-09-25",
    photos: { photo: ["/no-img.png"] },
    ville: "Marseille",
  },
  {
    title: "Opel Corsa Edition",
    marque: "Opel",
    modele: "Corsa",
    reference: "OPEL-COR-2020-011",
    version: "1.2 75",
    prixttcaffiche: 11990,
    kilometrage: 41000,
    anneemodele: "2020",
    energie: "Essence",
    carrosserie: "Citadine",
    nbrplace: 5,
    nbrporte: 5,
    couleurexterieur: "Jaune",
    puissancefiscale: 4,
    puissancedyn: 75,
    categorie: "Particulier",
    typeboite: "Manuelle",
    description: "Citadine récente, couleur vive.",
    datemes: "2021-04-11",
    photos: { photo: ["/no-img.png"] },
    ville: "Nice",
  },
  {
    title: "Toyota Yaris Hybride",
    marque: "Toyota",
    modele: "Yaris",
    reference: "TOY-YAR-2019-012",
    version: "Hybrid 100h",
    prixttcaffiche: 15490,
    kilometrage: 53000,
    anneemodele: "2019",
    energie: "Éléctrique",
    carrosserie: "Citadine",
    nbrplace: 5,
    nbrporte: 5,
    couleurexterieur: "Gris",
    puissancefiscale: 4,
    puissancedyn: 100,
    categorie: "Particulier",
    typeboite: "Automatique",
    description: "Hybride, très fiable et économique.",
    datemes: "2020-10-08",
    photos: { photo: ["/no-img.png"] },
    ville: "Dijon",
  },
];


